# Numpy 기초연습문제

In [1]:
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [11]:
a = np.zeros((3, 4))   # np.zeros를 이용하여 0으로 꽉찬 데이트 프레임 생성
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

numpy.ndarray

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [13]:
for i in range(a.shape[0]):         # shpae은 차원을 의미  / Shape(0) 은 3 
    for j in range(a.shape[1]):     # 간단하게 해석하면 2차원 for문 돌리는데 1번 배열 2번 배열 3번 배열 채워나가는 것
        a[i, j] = i*4 + j + 1       # i번째 배열의 j번째 값에 값을 넣는 것 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [14]:
num = 1
for i in range(a.shape[0]):        # 위와 마찬가지로 for문 돌리는것
    for j in range(a.shape[1]):
        a[i, j] =  num              # 다만 여기를 위처럼 나누지 않고 그냥 num 하나로 해서 계속 더함
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [16]:
a[1, 2]  # 1,2 값이므로 파이썬은 0부터 시작 따라서 1 = 2번째 배열 , 2 = 세번째 값 출력

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [18]:
a.shape     # 3개의 배열에 4개의 값이 있는 형태

(3, 4)

In [19]:
a[[1], :] # 2번째 배열의 모든 값 출력

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [21]:
a[:,[0, 2]] # 모든 배열의 첫번째 세번째 값 출력

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [22]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
# asarray는 데이터 타입이 다를 경우 적용 / for 문을 통해 값을 다 돌려 6보다 작은 값만 배열로 만듬
result

array([1., 2., 3., 4., 5., 6.])

In [23]:
a[a <= 6]  # a에서 값이 6보다 작은것 출력

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [29]:
b = np.random.random((3, 4))   # random.random 을 사용해 랜덤으로 배열 설정
b

array([[0.69523005, 0.15740887, 0.40393821, 0.810546  ],
       [0.75042375, 0.04616405, 0.16691594, 0.00247269],
       [0.27662645, 0.59390704, 0.77940132, 0.04738304]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [30]:
c = a * b  # a배열과 b배열 곱해서 c에 저장 / 순서에 맞게 알아서 곱해짐
c

array([[0.69523005, 0.31481774, 1.21181463, 3.24218398],
       [3.75211877, 0.27698429, 1.1684116 , 0.01978149],
       [2.48963807, 5.93907038, 8.57341448, 0.56859647]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [31]:
d = b.T
d

array([[0.69523005, 0.75042375, 0.27662645],
       [0.15740887, 0.04616405, 0.59390704],
       [0.40393821, 0.16691594, 0.77940132],
       [0.810546  , 0.00247269, 0.04738304]])

In [32]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [34]:
print(a.shape, d.shape)   # a의 차원과 d 차원 출력

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [35]:
e = a.dot(d)  # 행렬곱 함수인 dot을 사용
e

array([[ 5.46404641,  1.35339042,  3.99217664],
       [13.73253891,  5.21729615, 10.78144802],
       [22.00103142,  9.08120188, 17.57071941]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [37]:
np.sum(e, axis=1)  # 각 배열의 합을 계산

array([10.80961347, 29.73128309, 48.65295271])